### ISSUE TITLE
Erlang proxy installer

### ISSUE THREAD

**Issue by seriyps** [HirbodBehnam/MTProtoProxyInstaller#10]
FYI, I created interactive installer for Erlang proxy:

https://gist.github.com/seriyps/dc00ad91bfd8a2058f30845cd0daed83

https://github.com/seriyps/mtproto_proxy#how-to-install---one-line-interactive-installer

Maybe it makes sense to include it to your project?

**Comment by HirbodBehnam** [comment]
Wow nice! Sure I will just put the link in the readme file! Thanks again!

**Comment by HirbodBehnam** [comment]
Done! Added it in the latest commit.

**Comment by seriyps** [comment]
Thanks a lot!
