### ISSUE TITLE
FAKE TLS 

### ISSUE THREAD

**Issue by amidboys** [HirbodBehnam/MTProtoProxyInstaller#11]
Hello,
fake tls works on recent android and desktop telegram but does not works on ios!!!! can you help me?

**Comment by HirbodBehnam** [comment]
Hello
Does your secret begin with `7` or `ee`?

**Comment by HirbodBehnam** [comment]
If it starts with `7` it's a bug; described here: https://github.com/alexbers/mtprotoproxy/issues/115#issuecomment-519994184
You can upgrade the proxy and retrive the secret with `dd`.

**Comment by amidboys** [comment]
> Hello
> Does your secret begin with `7` or `ee`?

It starts with 7

**Comment by HirbodBehnam** [comment]
Use the latest version of the script and the problem will be solved

**Comment by amidboys** [comment]
> Use the latest version of the script and the problem will be solved.
> It will generate one that starts with `ee`

I've installed it through your installer package 2 days ago.  may I use Upgrade proxy software from your installer?

**Comment by HirbodBehnam** [comment]
No just type this command:
```
curl -o MTProtoProxyInstall.sh -L https://git.io/fjo34 && bash MTProtoProxyInstall.sh
```
and choose show proxy links.

**Comment by amidboys** [comment]
tnx, bro, it solved.

**Comment by HirbodBehnam** [comment]
yw
