### ISSUE TITLE
Separate NTP server is not needed on modern distributives

### ISSUE THREAD

**Issue by seriyps** [HirbodBehnam/MTProtoProxyInstaller#12]
You don't need to install ntp server to have server's time be automatically synced. Systemd has built-in ntp support. See https://gist.github.com/seriyps/dc00ad91bfd8a2058f30845cd0daed83#file-mtp_install-sh-L76 for example.

```
man timedatectl
sudo timedatectl set-ntp on
timedatectl timesync-status
```

**Comment by HirbodBehnam** [comment]
Oh thanks for the tip! I will change the script.
