### ISSUE TITLE
A question about Python one-click installation script.

### ISSUE THREAD

**Issue by z991238** [HirbodBehnam/MTProtoProxyInstaller#13]
He compiles and installs on Azure's VM and is stuck in test_socket, unable to proceed to the next step. Is there a good solution? Or if you have a telegram, I will try to contact you to solve it.

**Comment by HirbodBehnam** [comment]
Hello
You can contact me via @ThyCrow
Plus I have not worked with Azure or Google Cloud or AWS and I cannot confirm that the script works on them.
