### ISSUE TITLE
running on multiple port in Python Proxy

### ISSUE THREAD

**Issue by rezabagh** [HirbodBehnam/MTProtoProxyInstaller#15]
Hi 
Is there any possibility to run this proxy on multiple ports at the same time? I know it is possible to have multiple secrets on a single port but I could not figure out how I could run the proxy on multiple ports with different secrets. Would be helpful to advise. Thanks

**Comment by HirbodBehnam** [comment]
Hello
With my script, no;
You should manually clone and build the project in different directories. Then run and configure each of them on different port.
