### ISSUE TITLE
Some clients are unable to connect

### ISSUE THREAD

**Issue by Reza-JDP** [HirbodBehnam/MTProtoProxyInstaller#18]
@HirbodBehnam 

Hi,
I've noticed some random clients are unable to connect to the server i've started recently, While some other clients have no problems connecting to it.
I'm attaching my config file contents and the log from systemctl here to see if you can resolve the problem.
Config file:

```
PORT = 443
USER_MAX_TCP_CONNS = {  }
TLS_DOMAIN = "www.cloudflare.com"
MODES = { "classic": True, "secure": True, "tls": True }
USERS = {"mt1": "da911d79f646bfcfd4d64ac2f079e55e"}
```

systemctl log:
```
● mtprotoproxy.service - MTProto Proxy Service
   Loaded: loaded (/etc/systemd/system/mtprotoproxy.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2020-01-17 07:38:53 EST; 10s ago
 Main PID: 1855 (python3.6)
   CGroup: /system.slice/mtprotoproxy.service
           └─1855 /usr/bin/python3.6 /opt/mtprotoproxy/mtprotoproxy.py

Jan 17 07:38:53 server.domain.com systemd[1]: Started MTProto Proxy Service.
Jan 17 07:38:53 server.domain.com python3.6[1855]: mt1: tg://proxy?server=x.x.x.x&port=443&secret=eeda911d79f646bfcfd4d64ac2f079e55e7777772e636c6f7564666c6172652e636f6d
Jan 17 07:38:53 server.domain.com python3.6[1855]: Found uvloop, using it for optimal performance
Jan 17 07:38:53 server.domain.com python3.6[1855]: Got cert from the MASK_HOST www.cloudflare.com, its length is 2177
```

- Do i need to do anything for the TLS Host E.G registoring something, Or as a fake TLS i should just fill in the Hostname?
- Is anything wrong in my config file such as modes ETC which may not be compatible with some devices? If Yes, What modes should i choose?

I'm running Centos 7.7 on a server with 1 CPU Core and 1024MB of ram if it helps.
Thanks in advance!

**Comment by HirbodBehnam** [comment]
Hello
It might be your server that has been blocked, or if you are sharing it via a non fake-tls mode, it might be DPI just blocking the packets.
Either way I don't think this is an script issue. So I'll close this issue and you can open one here ()

And your questions:
1. No you just have to fill the field for fake tls.
2. Your config file is ok and it should support all of the Telegram clients that support fake tls. However, it's strongly recommended that you enable fake tls mode only and distribute it with fake tls mode.

**Comment by Reza-JDP** [comment]
@HirbodBehnam 
I don't get what you mean by "enable fake tls mode only and distribute it with fake tls mode."
May i have it explained please?

**Comment by HirbodBehnam** [comment]
I just meant "it's recommended to give the fake tls mode secret to users". Also in your config file, it looks like that you have enabled classic and random padding mode too. It is recommended to turn them off.

**Comment by Reza-JDP** [comment]
@HirbodBehnam Sorry if i'm asking too much. I'm fairly new to this.
If i'm not mistaken, According to what you've recommended the config file should look like this:
```
PORT = 443
USER_MAX_TCP_CONNS = {  }
TLS_DOMAIN = "www.cloudflare.com"
MODES = { "classic": False, "secure": False, "tls": True }
USERS = {"mt1": "da911d79f646bfcfd4d64ac2f079e55e"}
```

What do you mean by "giving fake TLS mode secret to users". I don't see how to get that.
Do you mean just enabling the TLS mode in configuration, or anything else should be done?
After editting the config file as you recommended, I see no changes in the secret string.

**Comment by HirbodBehnam** [comment]
@Reza-JDP Yep the config file is ok.

And the secret must start with ee. Secrets that start with ee are fake tls mode. Ones with dd are secure mode and without them are classic mode.

Also your clients might have to upgrade their telegram clients in order to use the fake tls mode.
