### ISSUE TITLE
Hello, how do I view the tg: // link, the systemctl status mtprotoproxy -l command does not see this 

### ISSUE THREAD

**Issue by oyanli** [HirbodBehnam/MTProtoProxyInstaller#19]
Hello, how do I view the tg: // link, the systemctl status mtprotoproxy -l command does not see this

**Comment by HirbodBehnam** [comment]
Sometimes after a while, proxy generates a lot of logs so you need to either restart the service or see the full log.
My prefered way is to rerun the script and use choose number 1 on the menu to see the links.
