### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by MohammadGIV** [HirbodBehnam/MTProtoProxyInstaller#20]
Hi.
I receive python error frequently at any part of script.
For example when i want to uninstall i receive:
MTProtoProxyInstall.sh: line 493: python3.6: command not found
I also updated and upgraded all packages.

**Comment by HirbodBehnam** [comment]
Hello
What is your OS?

**Comment by MohammadGIV** [comment]
Ubuntu 19.10 (GNU/Linux 5.3.0-29-generic x86_64)

**Comment by HirbodBehnam** [comment]
This script is not (yet) compatible with Ubuntu 19
