### ISSUE TITLE
How many connection needed for each user

### ISSUE THREAD

**Issue by A2116** [HirbodBehnam/MTProtoProxyInstaller#22]
in simultaneous connection limit, how many connections is needed for each telegram instance? 1 or more? is an app run better with more connections or they are not used?

**Comment by HirbodBehnam** [comment]
Hello
The number of connection for each client is at max 8. But you don't need to do the math because the script does it for you; For example if you input 1, script saves 8.

**Comment by A2116** [comment]
I am using the official script for its performance and manageability + port
forwarder, so I set user max connection in rules.json
is a user with 8 connection have better performance than user with 4
connection?
also, another thing is Forwarder_linux_amd64 file make rules.json
unreadable because it converts all return and tab and space to space and
destroys file structure

**Comment by HirbodBehnam** [comment]
Hello again
For the first question, yes 8 connections gives a better user experience than 4 connection. However it's not strict and 2 users _can_ connect to server. (However they have problem downloading files)
And for your other question; Json is meant to be machine readable and not human readable. You can use a json beautifier to just beautify it. Also note that beautifying json at the run time comes with resource cost and parsing and serializing a json without whitespace and tabs and new lines is faster.
