### ISSUE TITLE
Backup Possibility

### ISSUE THREAD

**Issue by A2116** [HirbodBehnam/MTProtoProxyInstaller#23]
I am running python server
How can backup server and client settings and transfer it to another server? is it possible?

**Comment by HirbodBehnam** [comment]
Hello
Yes. At first install the proxy on new server, (with my script) and then copy all `/opt/mtprotoproxy` to the new server and overwrite anything.

**Comment by A2116** [comment]
I am using centos, is any problem occur if centos version will upgrade from
7.4 to 8.1

**Comment by HirbodBehnam** [comment]
@A2116 This script might not work on Centos 8

**Comment by A2116** [comment]
if I want to upgrade to the new script that supports random padding and I copy all /opt/mtprotoproxy to new server then is the new script will work? or I should only transfer certain files to the new server?

**Comment by HirbodBehnam** [comment]
Hello
No I will not add backup support to script. You can manually copy the files as said. Also the script supports random padding you have to enable it when it's installing (as I said in your previous issue)
Also it's a good idea to copy all of the files to new server.

**Comment by A2116** [comment]
when I copy all files mtprotoproxy.py also will be copied and I think it's the main file
is this lead to revert to the old version or not?

**Comment by HirbodBehnam** [comment]
Please note that if you are going to use newer scripts with older MTproto installs, you might brick the config file.
So my best suggestion is to copy all of the files including the `mtprotoproxy.py` and script itself.
Now two things:
1. If you are going to upgrade the MTProtoProxy you can do it via script without any worries.
2. If you are going to upgrade the script itself, completely uninstall the MTproto proxy (without backups) and install a fresh one later. I do not grantee that the newer scripts are compatible with the older ones.

**Comment by A2116** [comment]
my main goal is to keep users and configs and upgrading server
so only thing that I need user keys and user limitations

**Comment by HirbodBehnam** [comment]
As I said, It's a good idea to copy everything including the script.

**Comment by A2116** [comment]
I copy all /opt/mtprotoproxy content to another place
then I copy mtprotoproxy.service and MTProtoProxyInstall.sh to another place
then I uninstall it using the script and remove MTProtoProxyInstall.sh file and download the new script using curl
then I installed the new script and create a new user and add all limitation to it to reproduce config files
by comparison of the new and old file, I recognized that the main structure does not change and so I copy config.py and limits_bash.txt and limits_date.json and limits_quota.json content to new files and restart the server
everything works fine and all users can connect using their old configurations
so I think migration process becomes completely successful
