### ISSUE TITLE
random padding vs fake tls

### ISSUE THREAD

**Issue by A2116** [HirbodBehnam/MTProtoProxyInstaller#26]
random padding vs fake tls
which one is better? more secure? more difficult to detect?
is it possible to use both of them? is it have any benefit?

**Comment by HirbodBehnam** [comment]
Hello
Fake TLS used to be better. I don't know about now.
Also yes they can be both enabled but they can't be used together; When the script asks you `Do want to restrict the connections?` select option number 2. (`"dd" secrets and TLS connections`)
And finally, I don't think that there is a benefit running them together.

**Comment by A2116** [comment]
if someone installs the script before this feature how should update it?
by updating software it does not update proxy abilities
and using random padding is impossible for old scripts
or even using without random padding and fake tls

**Comment by HirbodBehnam** [comment]
If you have used the old scripts you should uninstall the proxy first, then install using the newer scripts.
Scripts are not backward compatible.
