### ISSUE TITLE
proxy not work on iOS

### ISSUE THREAD

**Issue by sobhanso** [HirbodBehnam/MTProtoProxyInstaller#30]
Why does the proxy not work on iOS?

**Comment by HirbodBehnam** [comment]
Are you from Iran?

**Comment by sobhanso** [comment]
yes

**Comment by HirbodBehnam** [comment]
Most of the time, Iran's firewall actively blocks iOS connections. Nothing can't be done from script side.

**Comment by sobhanso** [comment]
But many proxies work well on the iOS !

**Comment by HirbodBehnam** [comment]
Yeah, in some servers, it works also on iOS.
I think that depends that if Iran has blacklisted your server or not; Which in this case I think they have.
