### ISSUE TITLE
uvloop Error

### ISSUE THREAD

**Issue by FemalePresident** [HirbodBehnam/MTProtoProxyInstaller#33]
After I clicked upgrade, I encountered the following error:

Requirement already satisfied: uvloop in /usr/local/lib/python3.6/dist-packages (0.14.0)
Collecting uvloop
  Downloading uvloop-0.15.1.tar.gz (2.1 MB)
     |################################| 2.1 MB 70.0 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3h928g6k/uvloop_929de4608798456f85f6d60da0bad337/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3h928g6k/uvloop_929de4608798456f85f6d60da0bad337/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ef4z4zab
         cwd: /tmp/pip-install-3h928g6k/uvloop_929de4608798456f85f6d60da0bad337/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3h928g6k/uvloop_929de4608798456f85f6d60da0bad337/setup.py", line 5, in <module>
        raise RuntimeError('uvloop requires Python 3.7 or greater')
    RuntimeError: uvloop requires Python 3.7 or greater
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/94/98/9dc814f391b2293ecc790b9752e005296c69c3694fd9975b6cb77c448135/uvloop-0.15.1.tar.gz#sha256=7846828112bfb49abc5fdfc47d0e4dfd7402115c9fde3c14c31818cfbeeb63dc (from https://pypi.org/simple/uvloop/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached uvloop-0.15.0.tar.gz (2.1 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3h928g6k/uvloop_5b84cbde046444d6b3626b4455c18d74/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3h928g6k/uvloop_5b84cbde046444d6b3626b4455c18d74/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-gl9swjz5
         cwd: /tmp/pip-install-3h928g6k/uvloop_5b84cbde046444d6b3626b4455c18d74/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3h928g6k/uvloop_5b84cbde046444d6b3626b4455c18d74/setup.py", line 5, in <module>
        raise RuntimeError('uvloop requires Python 3.7 or greater')
    RuntimeError: uvloop requires Python 3.7 or greater
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/df/fb/0e1b479ac5502f3d4531a2fc3f046312616f1ad020c686da353c2ff3bbc6/uvloop-0.15.0.tar.gz#sha256=1a503d5b49da6e3dd5607d6e533a5315b1caedbf629901807c65a23a09cad065 (from https://pypi.org/simple/uvloop/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Is there any good solution?
Thank you

**Comment by HirbodBehnam** [comment]
Hello
It looks like that uvloop 0.15 and higher have dropped python 3.6 support.
Will update the script to use older uvloop version.
Or maybe I check compatibility of mtproto with python 3.7 and use it.

**Comment by HirbodBehnam** [comment]
I think mtproto proxy supports python 3.8 as hinted in [docker file](https://github.com/alexbers/mtprotoproxy/blob/3b4f239cc15403bfb14f94f5b5b9212022a0e930/Dockerfile#L4)
Will update the script to use python 3.8
Thanks for reporting!
