### ISSUE TITLE
Official proxy failed with more than 16 secret

### ISSUE THREAD

**Issue by A2116** [HirbodBehnam/MTProtoProxyInstaller#35]
I am using the latest version of your script, but the official proxy won't work with more than 16 secret
is it the restriction on the main code or your script?
os is centos 8.3

**Comment by HirbodBehnam** [comment]
Hello
Yes there is a restriction on main code which does not allow more than 16 secrets.
Might add a limit to script as well to make sure users do not create more than 16 secrets.
