### ISSUE TITLE
MTProtoProxyInstall.sh: line 290: hexdump: command not found

### ISSUE THREAD

**Issue by commensal** [HirbodBehnam/MTProtoProxyInstaller#37]
-Ubuntu SMP Thu Jan 14 09:19:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

> Do you want to set secret manually or shall I create a random secret?
>    1) Manually enter a secret
>    2) Create a random secret
> Please select one [1-2]: 2
> MTProtoProxyInstall.sh: line 290: hexdump: command not found

**Comment by commensal** [comment]
apt-get install bsdmainutils

**Comment by nastyagrifon** [comment]
> apt-get install bsdmainutils

has solved "Bad secret for user %USERNAME%, should be 32 hex chars" for me. Script should definitely check for bsdmainutils and install if needed
