### ISSUE TITLE
آیا این ضد فیلتره؟

### ISSUE THREAD

**Issue by aliikarimi-crypto** [HirbodBehnam/MTProtoProxyInstaller#38]
**Important**
 - Please note that I'm not responsible if your server is blocked.
 - If your proxy does not work at all, please try again with a VPN and if it works, do not submit an issue.
 - Remove these lines before opening an issue.

**Describe the bug**

**Server:**
 - Server OS: 
 - Which script did you used? (Note that you must not open an issue about erlang script here)

**Comment by HirbodBehnam** [comment]
نه

**Comment by aliikarimi-crypto** [comment]
خب چه جوری میشه ضدفیلترش کرد
