### ISSUE TITLE
what is limit ? 

### ISSUE THREAD

**Issue by s-espriz** [HirbodBehnam/MTProtoProxyInstaller#39]
Hello 
thank you for your script 
the question is "What exactly the limit is?"
number of users or number of devics ? 

for example if i set it 1 can i use the proxy both in my android and desktop?

**Comment by HirbodBehnam** [comment]
Hello
Limit is the number of concurrent devices which you can connect with. For example one means that you can connect with your computer but not your phone.
Please be aware that limits are not accurate and thus you might be able to connect with two devices.

**Comment by s-espriz** [comment]
OK thanks
