### ISSUE TITLE
limit user

### ISSUE THREAD

**Issue by Mehdihp** [HirbodBehnam/MTProtoProxyInstaller#7]
limit user not working

**Comment by HirbodBehnam** [comment]
You need to install master branch in order to work. Enter these commands and post the output:
```
cd /opt/mtprotoproxy
git branch
```

**Comment by Mehdihp** [comment]
Is stable
How to install the script with -m argument to install the master.

**Comment by HirbodBehnam** [comment]
```
curl -o MTProtoProxyInstall.sh -L https://git.io/fjo34 && bash MTProtoProxyInstall.sh -m
```

**Comment by HirbodBehnam** [comment]
Also remember to uninstall the proxy at first then install the master branch using the code above.

**Comment by Mehdihp** [comment]
i was enter 1 but in config.py is 5 why?

**Comment by skipik** [comment]
https://github.com/HirbodBehnam/MTProtoProxyInstaller/blob/master/MTProtoProxyInstall.sh#L489
Is this line correct?

**Comment by HirbodBehnam** [comment]
@Mehdihp Because the proxy limits the users by connections not by the users. Each client of telegram establish more than ,4 or 5 connections. 
@skipik No it's not😂 Thanks for reporting.

**Comment by HirbodBehnam** [comment]
@Mehdihp Try the latest version now it might be ok. (Also install the master branch using the code above)
