### ISSUE TITLE
cant connect

### ISSUE THREAD

**Issue by PurTahan** [HirbodBehnam/MTProtoProxyInstaller#8]
Hi,
I use your solution for create my mtproto server
every things are good in installation, but i cant connect to it (from iran).
my server's ip is not blocked but i just connect to it with vpn.

can you help me to solve this problem?

**Comment by HirbodBehnam** [comment]
Hello
Unfortunately I can't help you with these cases. Some times DPI fully blocks the mtproto packets. You can try that on another server and it may work.
Also sometimes OVH hosting may block the packets.
For example my own server is from Eonix and and it works on it (although I do not use mtproto)
