### ISSUE TITLE
Hang

### ISSUE THREAD

**Issue by eroxs** [HirbodBehnam/MTProtoProxyInstaller#9]
Hi , when my connection close 1k per hour , my server connection lost and hanging , and i should start again

**Comment by HirbodBehnam** [comment]
Hello
At first I recommend to use the official one.
Secondly, do you think it is a script issue?

**Comment by HirbodBehnam** [comment]
Plus it could be also because of a low end server. If your proxy use alot of resources, the system will kill it.

**Comment by eroxs** [comment]
I want use TLS protocol , doesn't work in  official 
No my cpu and ram is high
4core and 8g ram

I think this script need edition 🤔👌

**Comment by HirbodBehnam** [comment]
The official script does not support the fake-tls yet.
Plus what did you select at the "how many workers do you want?"

**Comment by eroxs** [comment]
Yes when more than 1k connect to proxy , proxy disconnect and i must run again , although again hang when 1k

**Comment by HirbodBehnam** [comment]
When proxy disconnects can you run this command and post the output?
`systemctl status MTProxy`
(If you are using the official proxy)

**Comment by eroxs** [comment]
No official proxy
I talk about Fake TLS

**Comment by HirbodBehnam** [comment]
I have no clue what is your problem.
You mean on python proxy and fake TLS 1k users cannot connect?
Or what?

**Comment by eroxs** [comment]
Yes , after ~5min wen connection 1k 
Proxy hanging and should run script again

**Comment by HirbodBehnam** [comment]
You need to run my script again?
Ok two questions:
1. When you re-run my script, does it asks you to install from 0 or does it bring the post-install configuration panel?

2. After the proxy hangs, please run this command and post it's output:
`systemctl status mtprotoproxy -l)

**Comment by eroxs** [comment]
من خودم اجرا نکردم ولی دوستانم که کانال پراکسی دارن اجرا کردن اسکریپت رو ؛ و گفتن که وقتی امار میرسه به ۱کا ، هر ۵ مین کرش میکنه و کانکشن لاست میزنه و باید دوباره پراکسیو ران کنی

**Comment by HirbodBehnam** [comment]
این مشکل اسکریپت نیست بعضی وقتا خود پراکسی مخصوصا پایتون تحمل این قدر کانکشن رو ندارن.

**Comment by eroxs** [comment]
باید یه جوری رفع بشه وگرنه هیچکس نمیتونه خوب باهاش کار کنه

**Comment by HirbodBehnam** [comment]
خب خیلی های دیگه هم هستن از همین اسکریپت استفاده می کنن و راضی هستن.
می تونی اینو توی خود مشکلات پراکسی پایتون مطرح کنی:
https://github.com/alexbers/mtprotoproxy

**Comment by HirbodBehnam** [comment]
البته شاید هم به قول خودت واقعا مشکل اسکریپت باشه ولی من باید لاگ هارو داشته باشم تا بتونم بگم مشکل چیه

**Comment by HirbodBehnam** [comment]
درضمن اگر دنبال جایگزین هستی خود همون سورس ارلنگ رو امتحان کن.

**Comment by eroxs** [comment]
ارلنگ کدوم سورسه😐
الان همه‌ی سورسای غیر رسمی یه ایرادی دارن

**Comment by HirbodBehnam** [comment]
`curl -L -o mtp_install.sh https://git.io/fj5ru && bash mtp_install.sh` 
اینو اجرا کن.
راستی اگر سختته اینجا می تونیم توی تلگرام هم حرف بزنیم
آی دیم توی بیو همین جا هست

**Comment by eroxs** [comment]
Alexbers 
این مشکل تگ اسپانسر داره ، اسپانسر نشون نمیده

Seriyps 
این کلا پراکسی Secure رو میاره 
ولی fake tls رو نمیاره :|

**Comment by HirbodBehnam** [comment]
اگر مشکل tag داری این خط رو بزن:
aghar centos hasti:
```
yum install ntp
systemctl start ntpd
systemctl enable ntpd
reboot
```
این نشون میده که زمان سیستم شما مشکل داره و دقیق نیست اما با این احتمال زیاد درست میشه
